services:
  mongodb:
    container_name: mongo-db
    image: 'mongo:latest'
    environment:
      - 'MONGO_INITDB_DATABASE=pizza-hut'
      - 'MONGO_INITDB_ROOT_PASSWORD=secret'
      - 'MONGO_INITDB_ROOT_USERNAME=root'
    ports:
      - '27017:27017'

  rabbitmq:
    container_name: rabbitmq-microservice
    image: "rabbitmq:3.13.6-management"
    ports:
      - 5672:5672
      - 15672:15672
